name: 🚀 publish

on:
    push:
        branches: 
            - main

jobs:
  build:
    name: "🚀 build"
    runs-on: ubuntu-latest
    steps:
    - name: 📚 checkout
    - uses: actions/checkout@v2
    - name: 🟢 node
      uses: actions/setup-node@v1
      with:
        node-version: 15
    - run: npm ci
    - run: npm run build

  publish-npm:
    name: "🚀 publish"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: 📚 checkout
    - uses: actions/checkout@v2
    - name: 🟢 node
      uses: actions/setup-node@v1
      with:
        node-version: 15
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
